### ISSUE TITLE
Dashboard not showing

### ISSUE THREAD

**Issue by smarshallsay** [KevinJump/Our.Umbraco.BackOfficeThemes#16]
Hi Kevin,

I've added this via usync and I get an error and a blank tab:

`umbraco-backoffice-js.js.v1:formatted:17283 Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.0/$controller/ctrlreg?p0=backofficeThemeDashboardController
    at umbraco-backoffice-js.js.v1:formatted:13606
    at umbraco-backoffice-js.js.v1:formatted:16391
    at ea (umbraco-backoffice-js.js.v1:formatted:15852)
    at p (umbraco-backoffice-js.js.v1:formatted:15630)
    at g (umbraco-backoffice-js.js.v1:formatted:15439)
    at umbraco-backoffice-js.js.v1:formatted:15416
    at Object.link (umbraco-backoffice-js.js.v1:formatted:22642)
    at umbraco-backoffice-js.js.v1:formatted:13907
    at Ca (umbraco-backoffice-js.js.v1:formatted:16130)
    at p (umbraco-backoffice-js.js.v1:formatted:15679) '<div ng-include="property.view">'`

This seems similar to the issue I reported here for uSync: https://our.umbraco.com/forum/umbraco-9/106992-umbraco-9-usync-dashboard-not-loading-after-publish-to-server.
uSync and BackOfficeThemes are the only two extensions I have installed right now and uSync works fine. 
Am I doing something stupid?

I'm on the latest version of Umbraco 9

Thanks!

**Comment by smarshallsay** [comment]
It works fine on a fresh install of Umbraco, something else must be the culprit. Apologies!

**Comment by alfonso-jimenez-evelyn** [comment]
hi, what did you do to fix this error?
