### ISSUE TITLE
Umbraco 11 startup fails due to AddUnique() not found

### ISSUE THREAD

**Issue by tauremacar** [KevinJump/Our.Umbraco.BackOfficeThemes#25]
Umbraco v.11.1.0 fails to start with the following System.MissingMethodException

Message:
`Method not found: 'Void Umbraco.Extensions.ServiceCollectionExtensions.AddUnique(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.`

Source: Our.Umbraco.BackOfficeThemes

StackTrace:
```
   at Our.Umbraco.BackOfficeThemes.BackOfficeThemesComposer.Compose(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.Composing.ComposerGraph.Compose()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddComposers(IUmbracoBuilder builder)
   at ...
```

This can be related to the removal of obsolete extension methods in v.11:
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific/umbraco11-breaking-changes#umbraco.extensions

The error appears in .AddComposers() in Startup:

```
public void ConfigureServices(IServiceCollection services)
{
     services.AddUmbraco(_env, _config)
          .AddBackOffice()
          .AddWebsite()
          .AddComposers()
          ...
          .Build();

     ...
}
```

**Comment by KevinJump** [comment]
Fix in nightly if you want to test : 

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/Our.Umbraco.BackOfficeThemes/overview/3.0.1-build.20230126.1

**Comment by tauremacar** [comment]
It works! Thank you very much for this super fast action and response!
I haven't done any specific testing, but the site now starts and the previously selected theme shows up perfectly.

**Comment by alfonso-jimenez-evelyn** [comment]
Thanks , It works with nightly pre release version, i have one doubt, that version is gonna be the latest version or there are something else to build?

**Comment by KevinJump** [comment]
yeah not sure why we never published it as a release -- done now. v3.0.1
