### ISSUE TITLE
help to remove dashboard from settings tab

### ISSUE THREAD

**Issue by sekmenhuseyin** [KevinJump/Our.Umbraco.BackOfficeThemes#31]
is it possible to remove this dashboard from settings tab
![image](https://github.com/KevinJump/Our.Umbraco.BackOfficeThemes/assets/1363876/aa7b1745-2432-44a1-88fb-fccfe39303af)

**Comment by KevinJump** [comment]
Yeah - looking at the docs you can't because its a dashboard added via a package.manifest file, there is no way in Umbraco to programatically get rid of it. 😞 

- However it is any empty dashboard now. so I've removed it in the package.manifest file, so we can get rid of it in the package.

**Comment by sekmenhuseyin** [comment]
thank you
