### ISSUE TITLE
Unreadable icons

### ISSUE THREAD

**Issue by Ni-gashi** [KevinJump/Our.Umbraco.BackOfficeThemes#5]
**Describe the bug**
The icons in the Dark Theme are unreadable.

![image](https://user-images.githubusercontent.com/20931950/67457358-bb70af00-f633-11e9-8444-c2498c8d392d.png)

**To Reproduce**
1. Go to the "Document Types" and select some document type. 

**Expected behavior**
Add more contrast.

**Desktop (please complete the following information):**
 - Umbraco version 8.2.0
 - Firefox 69.0.3 (64-bit)

**Comment by KevinJump** [comment]
Fixed !! in 1.2 it looks all nice again :) 

![image](https://user-images.githubusercontent.com/431231/73444915-8326ee00-4351-11ea-877b-5c1809b3fd18.png)
